### PR TITLE
Hey, giving you me week 0 assignment

### PR DESCRIPTION
**Pull request by Anay121**
1. Learnt git & GitHub
1. Would have been better to do it yesterday
1. Learnt markdown too

### CODE REVIEW

**Comment by Korusuke** [comment]
not a good one onoy , but still i'll accept it , also its missing images , H1 , H2 tags , etc.

**Comment by Anay121** [comment]
It has an H1 tag !!!
Images haa, but its okay

**Comment by Korusuke** [comment]
kk no probs

**Comment by vtg2000** [comment]
its not good at all onoy..

**Pull request merged**
